

services:
  nginx:
    image: nginx:latest
  ports: 
    - "127.0.0.1:80:80" #Nginxはローカルホストからのみアクセス可能
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
  depends_on:
    -api


  api:
    image: go-lang:latest #使用するポストグレスのイメージ
    build: ./backend
    volumes:
      - db-data:/var/lib/postgres/data
    # ports:
    #   -"127.0.0.1:8080:8080"　#　ドッカーのネットワーク内でアクセスするため、外部に公開する設定を無効化
    depends_on:
      - db

  db:
    image: postgres:13 #データ永続かのためのボリューム
    environment:
         POSTGRES_USER: ${POSTGRES_USER}
         POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
         POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data #データ永続かのためのボリューム

volumes:
  db-data: #データベースのデータを永続するためのボリューム