

services:
  nginx:
    image: nginx:latest
  ports: 
    - "127.0.0.1:80:80" #Nginxはローカルホストからのみアクセス可能
    - "127.0.0.1:443:443" #Nginxはローカルホストからのみアクセス可能
  volumes:
    - ./proxyServer/nginx.conf:/etc/nginx/nginx.conf
    - ./proxyServer/certificate.crt:/etc/nginx/certificate.crt
    - ./proxyServer/private.key:/etc/nginx/private.key
  depends_on:
    - api


  api:
    image: go-lang:latest #使用するポストグレスのイメージ
    build: ./backend
    volumes:
      - db-data:/var/lib/postgres/data
    ports:
      -"127.0.0.1:8080:8080"
    depends_on:
      - db

  db:
    image: postgres:13 #データ永続かのためのボリューム
    build: ./backend/store
    ports:
      -"127.0.0.1:5432:5432"
    environment:
         POSTGRES_USER: ${POSTGRES_USER}
         POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
         POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data #データ永続かのためのボリューム

volumes:
  db-data: #データベースのデータを永続するためのボリューム