#ベースイメージとして公式のPostgresSQLイメージを使用
FROM postgres:latest

ENV POSTGRES_USER=MY_USER
ENV POSTGRES_PASSWORD=SAKUSAKU
ENV POSTGRES_DB=ORIGINAL_PROJECTS

#ポートを指定
EXPOSE 5432

#初期化スクリプトをコンテナにコピー
COPY ./init-db.sql /docker-entrypoint-initdb.d/

#コンテナが起動した時に実行されるコマンド
CMD ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]

