IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'MY_USER') THEN
	CREATE USER MY_USER WITH PASSWORD 'SAKUSAKU';
END IF;

IF NOT EXISTS (SELECT FROM pg_catalog.pg_database WHERE datname = 'ORIGINAL_PROJECTS') THEN
	CREATE DATABASE ORIGINAL_PROJECTS OWNER MY_USER;
END IF;


